import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    es: {
        events: 'Eventos',
        teams: 'Equipos',
        songs: 'Canciones',
        wall: 'El Muro',
        people: 'Personas',
        settings: 'Configuración',
        logout: 'Cerrar Sesión',
        hello: 'Hola',
        admin: 'Administrador',
        version: 'Versión',
        loading: 'Cargando ChurchTeams...',
        enterAnyway: 'Entrar de todos modos',
        clearSession: 'Limpiar sesión y reiniciar',
        footerText: 'Media EbenEzer Castellon',
        // Common
        add: 'Añadir',
        edit: 'Editar',
        delete: 'Eliminar',
        save: 'Guardar',
        cancel: 'Cancelar',
        confirm: 'Confirmar',
        search: 'Buscar',
        name: 'Nombre',
        email: 'Email',
        role: 'Rol',
        date: 'Fecha',
        time: 'Hora',
        location: 'Ubicación',
        description: 'Descripción',
        title: 'Título',
        actions: 'Acciones',
        noData: 'No hay datos',
        status: 'Estado',
        save_changes: 'Guardar Cambios',
        saving: 'Guardando...',
        updating: 'Actualizando...',
        error: 'Error',
        success: 'Éxito',
        // Events
        newEvent: 'Nuevo Evento',
        scheduleNewEvent: 'Programar Nuevo Evento',
        eventTitle: 'Título del Evento',
        eventTitlePlaceholder: 'Ej: Servicio de Domingo',
        noLocation: '(Sin ubicación)',
        serviceType: 'Tipo de Servicio',
        noCategory: '(Sin categoría)',
        descriptionPlaceholder: 'Detalles sobre el evento...',
        saveEvent: 'Programar Evento',
        editEvent: 'Editar Evento',
        updateEvent: 'Actualizar Evento',
        noEventsScheduled: 'No hay eventos programados.',
        confirmDeleteEvent: '¿Estás seguro de que quieres eliminar este evento?',
        eventDetails: 'Detalles del Evento',
        backToEvents: 'Volver a Eventos',
        // People
        peopleTitle: 'Personas',
        addPerson: 'Añadir Persona',
        newPerson: 'Nueva Persona',
        peopleDescription: 'Al añadir a alguien, se creará automáticamente su cuenta de acceso.',
        fullName: 'Nombre Completo',
        volunteer: 'Voluntario',
        teamLeader: 'Líder de Equipo',
        admin_role: 'Administrador',
        creatingAccount: 'Creando cuenta...',
        saveAndCreateAccount: 'Guardar y Crear Cuenta',
        searchPeople: 'Buscar personas...',
        availability: 'Disponibilidad',
        unavailableToday: 'No disponible hoy',
        available: 'Disponible',
        upcomingAbsences: 'Próximas ausencias:',
        to: 'al',
        userCreatedSuccess: '¡Usuario creado con éxito!',
        tempPassword: 'Contraseña temporal',
        notifyUserChangePassword: 'Indícale al usuario que cambie su contraseña al entrar.',
        emailAlreadyInUse: 'Este correo electrónico ya está registrado en la base de datos de autenticación.',
        noPeople: 'No hay personas registradas aún.',
        firstName: 'Nombre',
        lastName: 'Apellido',
        phone: 'Teléfono',
        confirmDeletePerson: '¿Estás seguro de que quieres eliminar a esta persona?',
        // Teams
        teamsTitle: 'Equipos',
        newTeam: 'Nuevo Equipo',
        createTeamTitle: 'Crear Nuevo Equipo',
        teamsDescription: 'Los equipos agrupan a las personas por su área de servicio.',
        teamName: 'Nombre del Equipo',
        teamNamePlaceholder: 'Ej: Alabanza',
        positions: 'Posiciones (separadas por comas)',
        positionsPlaceholder: 'Ej: Voz, Instrumento, Dirección',
        create: 'Crear',
        editTeam: 'Editar Equipo',
        manageMembers: 'Gestionar Miembros',
        close: 'Cerrar',
        searchPerson: 'Buscar persona...',
        members_count: 'Integrantes',
        noTeams: 'No hay equipos registrados.',
        confirmDeleteTeam: '¿Estás seguro de que quieres eliminar este equipo?',
        // Songs
        repertoire: 'Repertorio',
        songsDescription: 'Sube acordes, audios y gestiona las letras.',
        newSong: 'Nueva Canción',
        searchByTitle: 'Buscar por título...',
        artist: 'Artista',
        key: 'Tonalidad',
        chords: 'Acordes',
        audio: 'Audio',
        loadMore: 'Cargar más canciones',
        editSong: 'Editar Canción',
        lyrics: 'Letra',
        files: 'Archivos',
        pdfChords: 'PDF de Acordes',
        audioMp3: 'Audio MP3',
        externalUrl: 'O pegar URL externa (Drive/Dropbox)',
        uploading: 'Subiendo...',
        saveSong: 'Guardar Canción',
        confirmDeleteSong: '¿Estás seguro de eliminar esta canción?',
        errorSavingSong: 'Error al guardar la canción (verifica que Storage esté activo y el CORS configurado)',
        noSongs: 'No hay canciones registradas.',
        // Announcements
        wallTitle: 'El Muro',
        wallDescription: 'Comunícate con tus equipos y voluntarios.',
        newAnnouncement: 'Nuevo Memento',
        loadingAnnouncements: 'Cargando avisos...',
        noAnnouncementsWall: 'Aún no hay mensajes en el muro.',
        everyone: 'Todos',
        team: 'Equipo',
        editAnnouncement: 'Editar Memento',
        createAnnouncement: 'Crear Nuevo Memento',
        messageTitle: 'Título del mensaje',
        messageTitlePlaceholder: 'Ej: Ensayo de alabanza cancelado',
        targetAudience: 'Dirigido a:',
        allTeams: 'Todos los equipos',
        announcementType: 'Tipo de aviso:',
        general: 'General',
        important: 'Importante',
        urgent: 'Urgente',
        message: 'Mensaje',
        messagePlaceholder: 'Escribe aquí los detalles del anuncio...',
        publishMessage: 'Publicar Mensaje',
        confirmDeleteAnnouncement: '¿Eliminar este aviso?',
        errorPublishing: 'Error al publicar',
        alert: 'Alerta',
        info: 'Información',
        type: 'Tipo',
        content: 'Contenido',
        // Event Details

        published: 'Publicado',
        draft: 'Borrador',
        teamsAndPeople: 'Equipos y Personas',
        noOneAssigned: 'Nadie asignado aún.',
        confirmed: 'Confirmado',
        declined: 'Rechazado',
        pending: 'Pendiente',
        selectPerson: 'Selecciona persona...',
        notAvailable: '(NO DISPONIBLE)',
        noMembersInTeam: 'No hay miembros en este equipo',
        orderOfService: 'Orden de Servicio',
        noElementsDefined: 'No hay elementos definidos.',
        min: 'Min',
        momentPlaceholder: 'Momento (ej: Bienvenida)',
        noSong: '(Sin canción)',
        errorAssigning: 'Error al asignar',

        // Settings
        configTitle: 'Configuración',
        myAccount: 'Mi Cuenta',
        serviceTypes: 'Tipos de Servicio',
        locationsTitle: 'Lugares',
        rolesAndPermissions: 'Roles y Permisos',
        tags: 'Etiquetas',
        new: 'Nuevo',
        address: 'Dirección',
        addressOptional: 'Dirección (opcional)',
        namePlaceholder: 'Nombre (ej: Templo Principal)',

        confirmDeleteLocation: '¿Seguro que quieres eliminar este lugar?',
        noLocations: 'No has creado lugares.',
        serviceTypeName: 'Nombre del Servicio',
        serviceTypeNamePlaceholder: 'Ej: Servicio Dominical',
        defaultStartTime: 'Hora de inicio por defecto',
        confirmDeleteServiceType: '¿Eliminar este tipo de servicio?',
        noServiceTypes: 'No hay tipos de servicio.',
        roleName: 'Nombre del Rol',
        permissions: 'Permisos',
        confirmDeleteRole: '¿Eliminar este rol?',
        noRoles: 'No hay roles definidos.',
        tagName: 'Nombre de la etiqueta',
        tagColor: 'Color',
        confirmDeleteTag: '¿Eliminar esta etiqueta?',
        noTags: 'No hay etiquetas.',
        changePassword: 'Cambiar Contraseña',
        currentPassword: 'Contraseña Actual',
        newPassword: 'Nueva Contraseña',
        confirmNewPassword: 'Confirmar Nueva Contraseña',
        passwordChangedSuccess: 'Contraseña actualizada con éxito',
        errorChangingPassword: 'Error al cambiar la contraseña',
        commaSeparated: 'separados por coma',
        update: 'Actualizar',
        existingRoles: 'Roles existentes',
        newRole: 'Nuevo Rol',
        songTagsTitle: 'Etiquetas de Canciones',
        songTagDescription: 'Gestiona las categorías o etiquetas para organizar tu repertorio.',
        newTag: 'Nueva Etiqueta',
        editTag: 'Editar Etiqueta',
        tagPlaceholder: 'Ej: Adoración, Rápida, Himno...',
        personalInfo: 'Información Personal',


        securityPasswordNotice: 'Por seguridad, se te pedirá tu contraseña actual antes de establecer una nueva.',
        passwordsMismatch: 'Las contraseñas nuevas no coinciden.',
        passwordTooShort: 'La contraseña debe tener al menos 6 caracteres.',
        wrongPassword: 'La contraseña actual es incorrecta.',
        requiresRecentLogin: 'Por seguridad, debes cerrar sesión y volver a entrar para cambiar la contraseña.',
        profileUpdated: 'Perfil actualizado correctamente.',
        errorUpdatingProfile: 'Error al actualizar el perfil.',
        // Alerts
        assignmentDeclined: 'Asignación Rechazada',
        datesBlocked: 'Fechas Bloqueadas',
        notification: 'Notificación',
        declinedToServe: 'rechazó servir en',
        unavailable: 'no estará disponible',
        newSystemAlert: 'Nueva alerta del sistema.',
        notifications: 'Notificaciones',
        clearAll: 'Limpiar todo',
        noNewNotifications: 'No tienes notificaciones nuevas',
        today: 'Hoy'

    },



    ro: {
        events: 'Evenimente',
        teams: 'Echipe',
        songs: 'Cântări',
        wall: 'Anunțuri',
        people: 'Persoane',
        settings: 'Setări',
        logout: 'Deconectare',
        hello: 'Salut',
        admin: 'Administrator',
        version: 'Versiune',
        loading: 'Se încarcă ChurchTeams...',
        enterAnyway: 'Intră oricum',
        clearSession: 'Șterge sesiunea și repornește',
        footerText: 'Media EbenEzer Castellon',
        // Common
        add: 'Adaugă',
        edit: 'Editează',
        delete: 'Șterge',
        save: 'Salvează',
        cancel: 'Anulează',
        confirm: 'Confirmă',
        search: 'Caută',
        name: 'Nume',
        email: 'Email',
        role: 'Rol',
        date: 'Dată',
        time: 'Oră',
        location: 'Locație',
        description: 'Descriere',
        title: 'Titlu',
        actions: 'Acțiuni',
        noData: 'Nu sunt date',
        status: 'Status',
        save_changes: 'Salvează Modificările',
        saving: 'Se salvează...',
        updating: 'Se actualizează...',
        error: 'Eroare',
        success: 'Succes',
        // Events
        newEvent: 'Eveniment Nou',
        scheduleNewEvent: 'Programează Eveniment Nou',
        eventTitle: 'Titlul Evenimentului',
        eventTitlePlaceholder: 'Ex: Serviciu de Duminică',
        noLocation: '(Fără locație)',
        serviceType: 'Tipul Serviciului',
        noCategory: '(Fără categorie)',
        descriptionPlaceholder: 'Detalii despre eveniment...',
        saveEvent: 'Programează Eveniment',
        editEvent: 'Editează Eveniment',
        updateEvent: 'Actualizează Eveniment',
        noEventsScheduled: 'Nu sunt evenimente programate.',
        confirmDeleteEvent: 'Ești sigur că vrei să ștergi acest eveniment?',
        eventDetails: 'Detalii Eveniment',
        backToEvents: 'Înapoi la Evenimente',
        // People
        peopleTitle: 'Persoane',
        addPerson: 'Adaugă Persoană',
        newPerson: 'Persoană Nouă',
        peopleDescription: 'Când adaugi pe cineva, se va crea automat contul său de acces.',
        fullName: 'Nume Complet',
        volunteer: 'Voluntar',
        teamLeader: 'Lider de Echipă',
        admin_role: 'Administrator',
        creatingAccount: 'Se creează contul...',
        saveAndCreateAccount: 'Salvează și creează contul',
        searchPeople: 'Caută persoane...',
        availability: 'Disponibilitate',
        unavailableToday: 'Indisponibil astăzi',
        available: 'Disponibil',
        upcomingAbsences: 'Absențe următoare:',
        to: 'la',
        userCreatedSuccess: 'Utilizator creat cu succes!',
        tempPassword: 'Parolă temporară',
        notifyUserChangePassword: 'Anunță utilizatorul să își schimbe parola la intrare.',
        emailAlreadyInUse: 'Acest email este deja înregistrat în baza de date.',
        noPeople: 'Nu sunt persoane înregistrate încă.',
        firstName: 'Prenume',
        lastName: 'Nume de familie',
        phone: 'Telefon',
        confirmDeletePerson: 'Ești sigur că vrei să ștergi această persoană?',
        // Teams
        teamsTitle: 'Echipe',
        newTeam: 'Echipă Nouă',
        createTeamTitle: 'Creează Echipă Nouă',
        teamsDescription: 'Echipele grupează persoanele după aria lor de serviciu.',
        teamName: 'Numele Echipei',
        teamNamePlaceholder: 'Ex: Laudă și Închinare',
        positions: 'Poziții (separate prin virgulă)',
        positionsPlaceholder: 'Ex: Voce, Instrument, Direcție',
        create: 'Creează',
        editTeam: 'Editează Echipă',
        manageMembers: 'Gestionează Membrii',
        close: 'Închide',
        searchPerson: 'Caută persoană...',
        members_count: 'Membri',
        noTeams: 'Nu sunt echipe înregistrate.',
        confirmDeleteTeam: 'Ești sigur că vrei să ștergi această echipă?',
        // Songs
        repertoire: 'Repertoriu',
        songsDescription: 'Încarcă acorduri, audio și gestionează versurile.',
        newSong: 'Cântare Nouă',
        searchByTitle: 'Caută după titlu...',
        artist: 'Artist',
        key: 'Tonalitate',
        chords: 'Acorduri',
        audio: 'Audio',
        loadMore: 'Încarcă mai multe cântări',
        editSong: 'Editează Cântare',
        lyrics: 'Versuri',
        files: 'Fișiere',
        pdfChords: 'PDF Acorduri',
        audioMp3: 'Audio MP3',
        externalUrl: 'Sau lipește URL extern (Drive/Dropbox)',
        uploading: 'Se încarcă...',
        saveSong: 'Salvează Cântarea',
        confirmDeleteSong: 'Ești sigur că vrei să ștergi această cântare?',
        errorSavingSong: 'Eroare la salvarea cântării (verifică Storage și CORS)',
        noSongs: 'Nu sunt cântări înregistrate.',
        // Announcements
        wallTitle: 'Anunțuri',
        wallDescription: 'Comunică cu echipele și voluntarii tăi.',
        newAnnouncement: 'Anunț Nou',
        loadingAnnouncements: 'Se încarcă anunțurile...',
        noAnnouncementsWall: 'Nu sunt mesaje pe zid încă.',
        everyone: 'Toți',
        team: 'Echipă',
        editAnnouncement: 'Editează Anunț',
        createAnnouncement: 'Creează Anunț Nou',
        messageTitle: 'Titlul mesajului',
        messageTitlePlaceholder: 'Ex: Repetiția de laudă a fost anulată',
        targetAudience: 'Adresat către:',
        allTeams: 'Toate echipele',
        announcementType: 'Tipul anunțului:',
        general: 'General',
        important: 'Important',
        urgent: 'Urgent',
        message: 'Mesaj',
        messagePlaceholder: 'Scrie aici detaliile anunțului...',
        publishMessage: 'Publică Mesajul',
        confirmDeleteAnnouncement: 'Ștergi acest anunț?',
        errorPublishing: 'Eroare la publicare',
        alert: 'Alertă',
        info: 'Informație',
        type: 'Tip',
        content: 'Conținut',
        // Event Details

        published: 'Publicat',
        draft: 'Ciornă',
        teamsAndPeople: 'Echipe și Persoane',
        noOneAssigned: 'Nimeni asignat încă.',
        confirmed: 'Confirmat',
        declined: 'Refuzat',
        pending: 'În așteptare',
        selectPerson: 'Selectează persoana...',
        notAvailable: '(INDISPONIBIL)',
        noMembersInTeam: 'Nu sunt membri în această echipă',
        orderOfService: 'Ordinea de Serviciu',
        noElementsDefined: 'Nu sunt elemente definite.',
        min: 'Min',
        momentPlaceholder: 'Moment (ex: Bun venit)',
        noSong: '(Fără cântare)',
        errorAssigning: 'Eroare la asignare',

        // Settings
        configTitle: 'Configurare',
        myAccount: 'Contul Meu',
        serviceTypes: 'Tipuri de Serviciu',
        locationsTitle: 'Locații',
        rolesAndPermissions: 'Roluri și Permisiuni',
        tags: 'Etichete',
        new: 'Nou',
        address: 'Adresă',
        addressOptional: 'Adresă (opțional)',
        namePlaceholder: 'Nume (ex: Templul Principal)',

        confirmDeleteLocation: 'Sigur vrei să ștergi această locație?',
        noLocations: 'Nu ai creat locații.',
        serviceTypeName: 'Numele Serviciului',
        serviceTypeNamePlaceholder: 'Ex: Serviciu de duminică',
        defaultStartTime: 'Ora de start implicită',
        confirmDeleteServiceType: 'Ștergi acest tip de serviciu?',
        noServiceTypes: 'Nu sunt tipuri de serviciu.',
        roleName: 'Numele Rolului',
        permissions: 'Permisiuni',
        confirmDeleteRole: 'Ștergi acest rol?',
        noRoles: 'Nu sunt roluri definite.',
        tagName: 'Numele etichetei',
        tagColor: 'Culoare',
        confirmDeleteTag: 'Ștergi această etichetă?',
        noTags: 'Nu sunt etichete.',
        changePassword: 'Schimbă Parola',
        currentPassword: 'Parola Actuală',
        newPassword: 'Parola Nouă',
        confirmNewPassword: 'Confirmă Parola Nouă',
        passwordChangedSuccess: 'Parola a fost actualizată cu succes',
        errorChangingPassword: 'Eroare la schimbarea parolei',
        commaSeparated: 'separate prin virgulă',
        update: 'Actualizează',
        existingRoles: 'Roluri existente',
        newRole: 'Rol Nou',
        songTagsTitle: 'Etichete Cântări',
        songTagDescription: 'Gestionează categoriile sau etichetele pentru a-ți organiza repertoriul.',
        newTag: 'Etichetă Nouă',
        editTag: 'Editează Eticheta',
        tagPlaceholder: 'Ex: Închinare, Rapidă, Imn...',
        personalInfo: 'Informații Personale',


        securityPasswordNotice: 'Din motive de securitate, ți se va cere parola actuală înainte de a seta una nouă.',
        passwordsMismatch: 'Parolele noi nu coincid.',
        passwordTooShort: 'Parola trebuie să aibă cel puțin 6 caractere.',
        wrongPassword: 'Parola actuală este incorectă.',
        requiresRecentLogin: 'Din motive de securitate, trebuie să te reconectezi pentru a schimba parola.',
        profileUpdated: 'Profil actualizat cu succes.',
        errorUpdatingProfile: 'Eroare la actualizarea profilului.',
        // Alerts
        assignmentDeclined: 'Asignare Refuzată',
        datesBlocked: 'Date Blocate',
        notification: 'Notificare',
        declinedToServe: 'a refuzat să slujească la',
        unavailable: 'nu va fi disponibil',
        newSystemAlert: 'Alertă nouă de sistem.',
        notifications: 'Notificări',
        clearAll: 'Șterge tot',
        noNewNotifications: 'Nu ai notificări noi',
        today: 'Astăzi'

    },



    en: {
        events: 'Events',
        teams: 'Teams',
        songs: 'Songs',
        wall: 'The Wall',
        people: 'People',
        settings: 'Settings',
        logout: 'Log Out',
        hello: 'Hello',
        admin: 'Administrator',
        version: 'Version',
        loading: 'Loading ChurchTeams...',
        enterAnyway: 'Enter anyway',
        clearSession: 'Clear session and restart',
        footerText: 'Media EbenEzer Castellon',
        // Common
        add: 'Add',
        edit: 'Edit',
        delete: 'Delete',
        save: 'Save',
        cancel: 'Cancel',
        confirm: 'Confirm',
        search: 'Search',
        name: 'Name',
        email: 'Email',
        role: 'Role',
        date: 'Date',
        time: 'Time',
        location: 'Location',
        description: 'Description',
        title: 'Title',
        actions: 'Actions',
        noData: 'No data',
        status: 'Status',
        save_changes: 'Save Changes',
        saving: 'Saving...',
        updating: 'Updating...',
        error: 'Error',
        success: 'Success',
        // Events
        newEvent: 'New Event',
        scheduleNewEvent: 'Schedule New Event',
        eventTitle: 'Event Title',
        eventTitlePlaceholder: 'e.g. Sunday Service',
        noLocation: '(No location)',
        serviceType: 'Service Type',
        noCategory: '(No category)',
        descriptionPlaceholder: 'Details about the event...',
        saveEvent: 'Schedule Event',
        editEvent: 'Edit Event',
        updateEvent: 'Update Event',
        noEventsScheduled: 'No events scheduled.',
        confirmDeleteEvent: 'Are you sure you want to delete this event?',
        eventDetails: 'Event Details',
        backToEvents: 'Back to Events',
        // People
        peopleTitle: 'People',
        addPerson: 'Add Person',
        newPerson: 'New Person',
        peopleDescription: 'When you add someone, their access account will be created automatically.',
        fullName: 'Full Name',
        volunteer: 'Volunteer',
        teamLeader: 'Team Leader',
        admin_role: 'Administrator',
        creatingAccount: 'Creating account...',
        saveAndCreateAccount: 'Save and Create Account',
        searchPeople: 'Search people...',
        availability: 'Availability',
        unavailableToday: 'Unavailable today',
        available: 'Available',
        upcomingAbsences: 'Upcoming absences:',
        to: 'to',
        userCreatedSuccess: 'User created successfully!',
        tempPassword: 'Temporary password',
        notifyUserChangePassword: 'Tell the user to change their password when they log in.',
        emailAlreadyInUse: 'This email is already registered in the authentication database.',
        noPeople: 'No people registered yet.',
        firstName: 'First Name',
        lastName: 'Last Name',
        phone: 'Phone',
        confirmDeletePerson: 'Are you sure you want to delete this person?',
        // Teams
        teamsTitle: 'Teams',
        newTeam: 'New Team',
        createTeamTitle: 'Create New Team',
        teamsDescription: 'Teams group people by their service area.',
        teamName: 'Team Name',
        teamNamePlaceholder: 'e.g. Worship',
        positions: 'Positions (comma separated)',
        positionsPlaceholder: 'e.g. Vocals, Instrument, Direction',
        create: 'Create',
        editTeam: 'Edit Team',
        manageMembers: 'Manage Members',
        close: 'Close',
        searchPerson: 'Search person...',
        members_count: 'Members',
        noTeams: 'No teams registered.',
        confirmDeleteTeam: 'Are you sure you want to delete this team?',
        // Songs
        repertoire: 'Repertoire',
        songsDescription: 'Upload chords, audios and manage lyrics.',
        newSong: 'New Song',
        searchByTitle: 'Search by title...',
        artist: 'Artist',
        key: 'Key',
        chords: 'Chords',
        audio: 'Audio',
        loadMore: 'Load more songs',
        editSong: 'Edit Song',
        lyrics: 'Lyrics',
        files: 'Files',
        pdfChords: 'PDF Chords',
        audioMp3: 'Audio MP3',
        externalUrl: 'Or paste external URL (Drive/Dropbox)',
        uploading: 'Uploading...',
        saveSong: 'Save Song',
        confirmDeleteSong: 'Are you sure you want to delete this song?',
        errorSavingSong: 'Error saving song (verify Storage and CORS)',
        noSongs: 'No songs registered.',
        // Announcements
        wallTitle: 'The Wall',
        wallDescription: 'Communicate with your teams and volunteers.',
        newAnnouncement: 'New Memento',
        loadingAnnouncements: 'Loading announcements...',
        noAnnouncementsWall: 'No messages on the wall yet.',
        everyone: 'Everyone',
        team: 'Team',
        editAnnouncement: 'Edit Announcement',
        createAnnouncement: 'Create New Announcement',
        messageTitle: 'Message title',
        messageTitlePlaceholder: 'e.g. Worship practice cancelled',
        targetAudience: 'Targeted to:',
        allTeams: 'All teams',
        announcementType: 'Announcement type:',
        general: 'General',
        important: 'Important',
        urgent: 'Urgent',
        message: 'Message',
        messagePlaceholder: 'Write announcement details here...',
        publishMessage: 'Publish Message',
        confirmDeleteAnnouncement: 'Delete this notice?',
        errorPublishing: 'Error publishing',
        alert: 'Alert',
        info: 'Information',
        type: 'Type',
        content: 'Content',
        // Event Details

        published: 'Published',
        draft: 'Draft',
        teamsAndPeople: 'Teams & People',
        noOneAssigned: 'No one assigned yet.',
        confirmed: 'Confirmed',
        declined: 'Declined',
        pending: 'Pending',
        selectPerson: 'Select person...',
        notAvailable: '(NOT AVAILABLE)',
        noMembersInTeam: 'No members in this team',
        orderOfService: 'Order of Service',
        noElementsDefined: 'No elements defined.',
        min: 'Min',
        momentPlaceholder: 'Moment (e.g. Welcome)',
        noSong: '(No song)',
        errorAssigning: 'Error assigning',

        // Settings
        configTitle: 'Settings',
        myAccount: 'My Account',
        serviceTypes: 'Service Types',
        locationsTitle: 'Locations',
        rolesAndPermissions: 'Roles & Permissions',
        tags: 'Tags',
        new: 'New',
        address: 'Address',
        addressOptional: 'Address (optional)',
        namePlaceholder: 'Name (e.g. Main Temple)',

        confirmDeleteLocation: 'Are you sure you want to delete this location?',
        noLocations: 'No locations created.',
        serviceTypeName: 'Service Name',
        serviceTypeNamePlaceholder: 'e.g. Sunday Service',
        defaultStartTime: 'Default start time',
        confirmDeleteServiceType: 'Delete this service type?',
        noServiceTypes: 'No service types.',
        roleName: 'Role Name',
        permissions: 'Permissions',
        confirmDeleteRole: 'Delete this role?',
        noRoles: 'No roles defined.',
        tagName: 'Tag Name',
        tagColor: 'Color',
        confirmDeleteTag: 'Delete this tag?',
        noTags: 'No tags.',
        changePassword: 'Change Password',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmNewPassword: 'Confirm New Password',
        passwordChangedSuccess: 'Password updated successfully',
        errorChangingPassword: 'Error changing password',
        commaSeparated: 'comma separated',
        update: 'Update',
        existingRoles: 'Existing Roles',
        newRole: 'New Role',
        songTagsTitle: 'Song Tags',
        songTagDescription: 'Manage categories or tags to organize your repertoire.',
        newTag: 'New Tag',
        editTag: 'Edit Tag',
        tagPlaceholder: 'e.g. Worship, Fast, Hymn...',
        personalInfo: 'Personal Information',


        securityPasswordNotice: 'For security, you will be asked for your current password before setting a new one.',
        passwordsMismatch: 'The new passwords do not match.',
        passwordTooShort: 'The password must be at least 6 characters long.',
        wrongPassword: 'The current password is incorrect.',
        requiresRecentLogin: 'For security, you must log out and log back in to change your password.',
        profileUpdated: 'Profile updated successfully.',
        errorUpdatingProfile: 'Error updating profile.',
        // Alerts
        assignmentDeclined: 'Assignment Declined',
        datesBlocked: 'Dates Blocked',
        notification: 'Notification',
        declinedToServe: 'declined to serve in',
        unavailable: 'will not be available',
        newSystemAlert: 'New system alert.',
        notifications: 'Notifications',
        clearAll: 'Clear all',
        noNewNotifications: 'No new notifications',
        today: 'Today'

    }



};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('appLanguage') || 'es');

    useEffect(() => {
        localStorage.setItem('appLanguage', language);
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
